# Цель для вывода справки
help:
	@echo "Используйте следующие команды:"
	@echo "  make dev                - Запустить приложение"
	@echo "  make build              - Сделать билд приложения"
	@echo "  make shadcn-add         - Создает компоненты на основе shadcn"

shadcn-add:
	bun run shadcn-add

# Команда старта
dev:
	bun run dev

# Команда билда
build:
	bun run build

.PHONY: help build start