"""empty message

Revision ID: 68c22525f815
Revises: c372f0770a9e
Create Date: 2025-03-21 21:07:11.552170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68c22525f815"
down_revision: Union[str, None] = "c372f0770a9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("username", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "username")
    # ### end Alembic commands ###
